export const corais = [
  {
    grupo: 'SOFTS',
    especie: 'ACTINODISCUS SP',
    nomepopular: 'MUSHROOM',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://vividaquariums.com/cdn/shop/products/FJ6A1440_384x384.jpg?v=1668878817',
    ___id___: '1'
  },
  {
    grupo: 'SOFTS',
    especie: 'BRIAREUM SP',
    nomepopular: 'STAR POLYPS',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Baixa',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2022/03/15117623955_CoralClub-Coral-Soft-Green-Star-Polyps.jpg?fit=600%2C600&ssl=1',
    ___id___: '2'
  },
  {
    grupo: 'SOFTS',
    especie: 'CAPNELLA SP',
    nomepopular: 'KENYA TREE',
    crescimento: 'Para cima',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Média',
    cores: [ 'Marrom' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/06/15195676299_CoralClub-Soft-Kenia-Tree.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '3'
  },
  {
    grupo: 'SOFTS',
    especie: 'CLADIELLA SP',
    nomepopular: 'COLT',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Marrom' ],
    imagem: 'https://www.aquariumcreationsonline.net/images/ColtCoral650x515.jpg',
    ___id___: '4'
  },
  {
    grupo: 'SOFTS',
    especie: 'CLAVULARIA SP',
    nomepopular: 'CLOVES',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Laranja' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2024/02/15251027501_CoralClub-Soft-Cloves-Brown.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '5'
  },
  {
    grupo: 'SOFTS',
    especie: 'DISCOSOMA SP',
    nomepopular: 'MUSHROOM',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/07/CoralClub-Soft-CC-Rainbow-Mushroom.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '6'
  },
  {
    grupo: 'SOFTS',
    especie: 'LOBOPHYTUM SP',
    nomepopular: 'LEATHER DEVILS HAND',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Marrom', ' Verde' ],
    imagem: 'https://vividaquariums.com/cdn/shop/products/DevilsHandLeather4_2000x2000.jpg?v=1647132154',
    ___id___: '7'
  },
  {
    grupo: 'SOFTS',
    especie: 'PALYTHOA SP',
    nomepopular: 'PALYTHOA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/07/15202149614_CoralClub-Soft-Palythoa-Magician-B.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '8'
  },
  {
    grupo: 'SOFTS',
    especie: 'PARAZOANTHUS SP',
    nomepopular: 'YELLOW POLYPS',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Amarelo' ],
    imagem: 'https://www.shutterstock.com/image-photo/yellow-polyps-parazoanthus-gracilis-260nw-1030996864.jpg',
    ___id___: '9'
  },
  {
    grupo: 'SOFTS',
    especie: 'RHODACTIS SP',
    nomepopular: 'MUSHROOM RHODACTIS',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/09/15214839595_CoralClub-Soft-Mush-Combo.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '10'
  },
  {
    grupo: 'SOFTS',
    especie: 'RICORDEA FLORIDA',
    nomepopular: 'RICORDEA FLORIDA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Laranja', ' Azul', ' Verde' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/07/CoralClub-Soft-Ricordea-Florida-Green-C.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '11'
  },
  {
    grupo: 'SOFTS',
    especie: 'RICORDEA YUMA',
    nomepopular: 'RICORDEA YUMA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://reeffishcenter.shop/2151-large_default/ricordea-yuma-exotic-orangegreen-1-ear-.jpg',
    ___id___: '12'
  },
  {
    grupo: 'SOFTS',
    especie: 'SARCOPHYTON SP',
    nomepopular: 'LEATHER UMBRELLA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Amarelo' ],
    imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDFOt4HvkQD6vPCpm4jzaHzNFV8Cvy-eKtWwdfsvxGzA&s',
    ___id___: '13'
  },
  {
    grupo: 'SOFTS',
    especie: 'SINULARIA SP',
    nomepopular: 'LEATHER FINGER',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2024/03/15258314127_CoralClub-Soft-Leather-Finger-Neon.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '14'
  },
  {
    grupo: 'SOFTS',
    especie: 'TUBIPORA MUSICA',
    nomepopular: 'ORGAN PIPE',
    crescimento: 'Para os lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Branco' ],
    imagem: 'https://reeffishcenter.shop/2410-large_default/tubipora-musica-green-s-size.jpg',
    ___id___: '15'
  },
  {
    grupo: 'SOFTS',
    especie: 'XENIA SP',
    nomepopular: 'XENIA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Alta',
    circulacao: 'Baixa',
    cores: [ 'Marrom', ' Azul', ' Branco' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2024/02/15251161076_CoralClub-Soft-Xenia-Giant.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '16'
  },
  {
    grupo: 'SOFTS',
    especie: 'ZOANTHUS SP',
    nomepopular: 'ZOANTHUS',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2024/04/15263395610_CoralClub-Soft-Zoanthus-Alfa-Omega.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '17'
  },
  {
    grupo: 'LPS',
    especie: 'ACANTHASTREA ECHINATA',
    nomepopular: 'ACAN ECHINATA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Marrom', ' Verde', ' Vermelho', ' Laranja' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2024/02/15253754784_CoralClub-LPS-Acan-Echinata-Rainbow-1.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '18'
  },
  {
    grupo: 'LPS',
    especie: 'ALVEOPORA SP',
    nomepopular: 'ALVEOPORA',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Marrom', ' Verde' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/03/Alveopora.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '19'
  },
  {
    grupo: 'LPS',
    especie: 'BLASTOMUSSA MERLETI',
    nomepopular: 'BLASTO MERLETI',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Verde', ' Vermelho', ' Roxo' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2021/11/15095110270_coralclub-lps-blastomussa-merletti-red.jpg?fit=600%2C600&ssl=1',
    ___id___: '20'
  },
  {
    grupo: 'LPS',
    especie: 'BLASTOMUSSA WELLSI',
    nomepopular: 'BLASTO WELLSI',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Verde', ' Vermelho', ' Laranja' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/07/CoralClub-LPS-Blastomussa-Welssi-Purple-B.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '21'
  },
  {
    grupo: 'LPS',
    especie: 'CATALAPHYLLIA JARDINEI',
    nomepopular: 'ELEGANCE',
    crescimento: 'Para os lados',
    dificuldade: 'Média',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Verde' ],
    imagem: 'https://www.coral.zone/wp-content/uploads/2022/03/c31047-b.jpg',
    ___id___: '22'
  },
  {
    grupo: 'LPS',
    especie: 'CAULASTREA SP',
    nomepopular: 'TRUMPET',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Verde' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/07/15202087921_Trumpet-Green.webp?fit=1200%2C1200&ssl=1',
    ___id___: '23'
  },
  {
    grupo: 'LPS',
    especie: 'CYNARINA LACRYMALIS',
    nomepopular: 'CYNARINA',
    crescimento: 'Para os lados',
    dificuldade: 'Baixa',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Verde', ' Vermelho' ],
    imagem: 'https://www.shutterstock.com/image-photo/truly-amazing-orange-cynarina-lacrymalis-600nw-2404110411.jpg',
    ___id___: '24'
  },
  {
    grupo: 'LPS',
    especie: 'CYPHASTREA SP',
    nomepopular: 'CYPHASTREA',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Laranja' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2024/04/15263483438_CoralClub-LPS-Cyphastrea-Four-Colors-B.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '25'
  },
  {
    grupo: 'LPS',
    especie: 'DUNCANOPSAMMIA AUXIFUGA',
    nomepopular: 'DUNCAN',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Verde' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/03/image_adobe_express-3.jpeg?fit=1080%2C1080&ssl=1',
    ___id___: '26'
  },
  {
    grupo: 'LPS',
    especie: 'ECHINOPHYLLIA SP',
    nomepopular: 'CHALICE',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Média',
    iluminacao: 'Baixa',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Rosa', ' Roxo', ' Laranja' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2023/04/CoralClub-LPS-Chalice-Golden-Eye.jpg?fit=1200%2C1200&ssl=1',
    ___id___: '27'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA ANCORA',
    nomepopular: 'HAMMER WALL',
    crescimento: 'Para os lados',
    dificuldade: 'Alta',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde', ' Rosa', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5996-large_default/euphyllia-ancora-sp-hammer-coral.jpg',
    ___id___: '28'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA CRISTATA',
    nomepopular: 'TORCH CRISTATA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde', ' Rosa', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5088-large_default/euphyllia-cristata-per-head.jpg',
    ___id___: '29'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA DIVISA',
    nomepopular: 'FROG WALL',
    crescimento: 'Para os lados',
    dificuldade: 'Média',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde', ' Rosa', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5550-large_default/euphyllia-divisa-frogspawn-green-m-size.jpg',
    ___id___: '30'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA GLABRESCENS',
    nomepopular: 'TORCH',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde', ' Rosa', ' Laranja' ],
    imagem: 'https://i0.wp.com/coralclub.live/wp-content/uploads/2021/11/15095041199_15095040652_coralclub-coral-torch-dragon-soul-2.jpg?fit=600%2C600&ssl=1',
    ___id___: '31'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA PARAANCORA',
    nomepopular: 'HAMMER',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde', ' Rosa', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5696-large_default/euphyllia-paraancora-green-purple-tips-hammer-coral.jpg',
    ___id___: '32'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA PARADIVISA',
    nomepopular: 'FROGSPAWN',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde', ' Rosa', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5537-large_default/euphyllia-paradivisa-orange-frogspawn-coral-orange-per-head.jpg',
    ___id___: '33'
  },
  {
    grupo: 'LPS',
    especie: 'EUPHYLLIA YAEYAMAENSIS',
    nomepopular: 'FROG YAMAMENSIS',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom.', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/4947-large_default/euphyllia-yaeyamaensis-gold-per-head.jpg',
    ___id___: '34'
  },
  {
    grupo: 'LPS',
    especie: 'FAVIA SP',
    nomepopular: 'FAVIA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Vermelho' ],
    imagem: 'https://reeffishcenter.shop/6031-large_default/favia-speciosa-brain-coral-green-with-red-eyes.jpg',
    ___id___: '35'
  },
  {
    grupo: 'LPS',
    especie: 'FAVITES SP ',
    nomepopular: 'FAVITES',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Vermelho', ' Amarelo' ],
    imagem: 'https://reeffishcenter.shop/5501-large_default/favites-sp-green-red-rim-m-size.jpg',
    ___id___: '36'
  },
  {
    grupo: 'LPS',
    especie: 'FUNGIA SP',
    nomepopular: 'PLATE',
    crescimento: 'Para os lados',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Verde', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5219-large_default/fungia-sp-orange-australia-plate-coral.jpg',
    ___id___: '37'
  },
  {
    grupo: 'LPS',
    especie: 'GALAXEA SP',
    nomepopular: 'GALAXEA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/5366-large_default/galaxea-fascicularis-spp.jpg',
    ___id___: '38'
  },
  {
    grupo: 'LPS',
    especie: 'GONIASTREA SP',
    nomepopular: 'GONIASTREA',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Verde' ],
    imagem: 'https://reeffishcenter.shop/6048-large_default/goniastrea-sp.jpg',
    ___id___: '39'
  },
  {
    grupo: 'LPS',
    especie: 'GONIOPORA SP',
    nomepopular: 'GONIOPORA',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Rosa', ' Vermelho' ],
    imagem: 'https://reeffishcenter.shop/2862-large_default/goniopora-green-golf-ball-s-size.jpg',
    ___id___: '40'
  },
  {
    grupo: 'LPS',
    especie: 'HELIOFUNGIA ACTINIFORMIS',
    nomepopular: 'PLATE LONG TENTACLE',
    crescimento: 'Para os lados',
    dificuldade: 'Média',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Rosa' ],
    imagem: 'https://reeffishcenter.shop/5383-large_default/heliofungia-actiniformis-sp-long-tentacle-plate-coral.jpg',
    ___id___: '41'
  },
  {
    grupo: 'LPS',
    especie: 'HOMOPHYLLIA AUSTRALIS',
    nomepopular: 'SCOLYMIA AUSTRALIANA',
    crescimento: 'Para os lados',
    dificuldade: 'Média',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Verde', ' Vermelho', ' Laranja', ' Roxo' ],
    imagem: 'https://reeffishcenter.shop/1791-large_default/scolymia-doughnut-coral-red-australia.jpg',
    ___id___: '42'
  },
  {
    grupo: 'LPS',
    especie: 'LOBOPHYLLIA SP',
    nomepopular: 'LOBO',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Variadas' ],
    imagem: 'https://reeffishcenter.shop/4419-large_default/lobophyllia-corymbosa-green-l-size.jpg',
    ___id___: '43'
  },
  {
    grupo: 'LPS',
    especie: 'MICROMUSSA LORDHOWENSIS',
    nomepopular: 'ACAN LORD',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Variadas' ],
    imagem: 'https://reeffishcenter.shop/5152-large_default/acanthastrea-lordhowensis-b-grade.jpg',
    ___id___: '44'
  },
  {
    grupo: 'LPS',
    especie: 'PARASCOLYMIA VITIENSIS',
    nomepopular: 'SCOLYMIA VITIENSIS',
    crescimento: 'Para os lados',
    dificuldade: 'Baixa',
    agressividade: 'Média',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Vermelho', ' Laranja' ],
    imagem: 'https://reeffishcenter.shop/5000-home_default/scolymia-doughnut-coral-ultra-green-australia.jpg',
    ___id___: '45'
  },
  {
    grupo: 'LPS',
    especie: 'PHYSOGYRA LICHTENSTEINI',
    nomepopular: 'PEARL',
    crescimento: 'Para os lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Marrom', ' Branco', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/5349-large_default/physogyra-lichtensteinii-pearl-bubble-coral-australie.jpg',
    ___id___: '46'
  },
  {
    grupo: 'LPS',
    especie: 'PLATYGYRA SP',
    nomepopular: 'PLATYGYRA',
    crescimento: 'Encrustante',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde', ' Roxo' ],
    imagem: 'https://reeffishcenter.shop/5582-large_default/platygyra-sp-green.jpg',
    ___id___: '47'
  },
  {
    grupo: 'LPS',
    especie: 'PLEOGYRA SINUOSA',
    nomepopular: 'BUBBLE',
    crescimento: 'Para os lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Baixa',
    cores: [ 'Marrom', ' Branco', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/5347-large_default/plerogyra-sinuosa-pearl-bubble-coral.jpg',
    ___id___: '48'
  },
  {
    grupo: 'LPS',
    especie: 'TRACHYPHYLLIA GEOFFROYI',
    nomepopular: 'OPEN BRAIN',
    crescimento: 'Para os lados',
    dificuldade: 'Baixa',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Rosa', ' Verde', ' Vermelho' ],
    imagem: 'https://reeffishcenter.shop/5607-large_default/trachyphyllia-geoffroyi-brain-coral-master-australie-ml.jpg',
    ___id___: '49'
  },
  {
    grupo: 'SPS',
    especie: 'ACROPORA MILLEPORA',
    nomepopular: 'MILLEPORA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Variadas' ],
    imagem: 'https://tidalgardens.com/media/catalog/product/2/4/2474-stock_1.jpg?width=265&height=265&store=default&image-type=image',
    ___id___: '50'
  },
  {
    grupo: 'SPS',
    especie: 'ACROPORA SP',
    nomepopular: 'ACROPORA',
    crescimento: 'Para cima e lados / Para os lados',
    dificuldade: 'Alta',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Variadas' ],
    imagem: 'https://reeffishcenter.shop/5404-large_default/acropora-sp-indonesia-mix-colors.jpg',
    ___id___: '51'
  },
  {
    grupo: 'SPS',
    especie: 'HYDNOPHORA SP',
    nomepopular: 'HYDNOPHORA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/5508-large_default/hydnophora-spp-green-horn-coral-australie.jpg',
    ___id___: '52'
  },
  {
    grupo: 'SPS',
    especie: 'MONTIPORA CAPRICORNIS',
    nomepopular: 'CAPRICÓRNIO',
    crescimento: 'Para os lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Laranja', ' Rosa', ' Verde' ],
    imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvLfPiEMGrbZ9WUAWPozN6EtJmSxVNNjeWFu-oW0eWF5LWE-cFE4fNXRS5kxAymJ5_T1E&usqp=CAU',
    ___id___: '53'
  },
  {
    grupo: 'SPS',
    especie: 'MONTIPORA DANAE',
    nomepopular: 'MONTIPORA DANAE',
    crescimento: 'Encrustante',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Variadas' ],
    imagem: 'https://zeeaquarium-winkel.nl/content/Products/montipora-danae-112731969.jpg',
    ___id___: '54'
  },
  {
    grupo: 'SPS',
    especie: 'MONTIPORA DIGITATA',
    nomepopular: 'DIGITATA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Variadas' ],
    imagem: 'https://reeffishcenter.shop/311-large_default/montipora-digitata-red.jpg',
    ___id___: '55'
  },
  {
    grupo: 'SPS',
    especie: 'PAVONA CACTUS',
    nomepopular: 'PAVONA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Baixa',
    agressividade: 'Alta',
    iluminacao: 'Média',
    circulacao: 'Média',
    cores: [ 'Marrom', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/6164-large_default/pavona-cactus-sp.jpg',
    ___id___: '56'
  },
  {
    grupo: 'SPS',
    especie: 'POCILLOPORA SP',
    nomepopular: 'POCCILOPORA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Roxo', ' Rosa', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/5453-large_default/pocillopora-spp-green.jpg',
    ___id___: '57'
  },
  {
    grupo: 'SPS',
    especie: 'PORITES SP',
    nomepopular: 'PORITES',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Marrom', ' Amarelo' ],
    imagem: 'https://reeffishcenter.shop/3186-large_default/porites-bisperma-spp-christmas-tree-worm-on-rock-m-size.jpg',
    ___id___: '58'
  },
  {
    grupo: 'SPS',
    especie: 'SERIATOPORA HYSTRIX',
    nomepopular: 'SERIATOPORA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Marrom', ' Roxo', ' Rosa', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/5450-large_default/seriatopora-hystrix-pink-birdnest-coral.jpg',
    ___id___: '59'
  },
  {
    grupo: 'SPS',
    especie: 'STYLOPHORA PISTILLATA',
    nomepopular: 'STYLOPHORA',
    crescimento: 'Para cima e lados',
    dificuldade: 'Média',
    agressividade: 'Baixa',
    iluminacao: 'Alta',
    circulacao: 'Alta',
    cores: [ 'Roxo', ' Rosa', ' Verde' ],
    imagem: 'https://reeffishcenter.shop/4369-large_default/stylophora-pistillata-green-polyp-m-size.jpg',
    ___id___: '60'
  }
]
